apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pagamento-deployment
  labels:
    app: pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagamento
  template:
    metadata:
      labels:
        app: pagamento
    spec:
      containers:
        - name: app-pagamento-container
          image: 807550779778.dkr.ecr.us-east-1.amazonaws.com/fiap-pagamento
          ports:
            - containerPort: 80
          env:
            - name: POSTGRE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: app-pagamento-opaque
                  key: POSTGRE_CONNECTION_STRING
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-pagamento-config
                  key: ASPNETCORE_ENVIRONMENT
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-pagamento-config
data:
  ASPNETCORE_ENVIRONMENT: "DEVELOPMENT"
