apiVersion: v1
kind: Service
metadata:
  name: app-pagamento-service
spec:
  selector:
    app: pagamento
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31301
  type: LoadBalancer
